language: android
android:
  components:
    - tools
    - build-tools-27.0.3
    - android-27
    - sys-img-armeabi-v7a-android-27
before_install:
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "build-tools;27.0.3"
jdk:
    - oraclejdk8
script:
    - ./gradlew clean build connectedCheck