language: android
android:
  components:
    - tools
    - build-tools-27.0.2
    - android-27
before_install:
    - yes | sdkmanager "platforms;android-27"
    - yes | sdkmanager "build-tools;27.0.1"
    - yes | sdkmanager "build-tools;27.0.2"
jdk:
    - oraclejdk8
script:
    - ./gradlew clean build